# GolangCI-Lint Configuration
# https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m
  issues-exit-code: 1
  tests: true

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters:
  enable:
    # Default linters
    - errcheck          # Check for unchecked errors
    - gosimple          # Simplify code
    - govet             # Reports suspicious constructs
    - ineffassign       # Detects unused assignments
    - staticcheck       # Static analysis
    - unused            # Checks for unused code

    # Additional safety linters
    - bodyclose         # Checks HTTP response body is closed
    - durationcheck     # Check for two durations multiplied
    - copyloopvar       # Checks for pointers to loop variables (Go 1.22+)
    - gocritic          # Comprehensive linter
    - gofmt             # Check formatting
    - goimports         # Check imports
    - gosec             # Security issues
    - makezero          # Finds slice declarations not initialized to zero
    - nilerr            # Finds returning nil when err is not nil
    - noctx             # Finds http requests without context
    - predeclared       # Find shadowed predeclared identifiers
    - reassign          # Checks that package variables are not reassigned
    - rowserrcheck      # Checks sql.Rows.Err is checked
    - sqlclosecheck     # Checks sql.Rows and sql.Stmt are closed
    - unconvert         # Remove unnecessary type conversions
    - wastedassign      # Finds wasted assignment statements

    # Style linters
    - misspell          # Finds commonly misspelled words
    - revive            # Replacement for golint
    - stylecheck        # Style checks
    - whitespace        # Whitespace issues

  disable:
    - contextcheck      # Too strict for our HTTP handler patterns
    - errname           # Allow internal error naming flexibility
    - errorlint         # Allow direct error comparison in tests
    - exhaustive        # Allow non-exhaustive switches with default
    - prealloc          # Optimization suggestion, not critical
    - unparam           # Too strict for interface implementations
    - gochecknoglobals  # We use some globals for config
    - gochecknoinits    # We use init() sparingly
    - lll               # Line length - too restrictive
    - wsl               # Whitespace linter - too opinionated
    - funlen            # Function length - handled by review
    - gocognit          # Cognitive complexity - handled by review
    - godox             # TODO/FIXME comments - we use these

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: false  # Allow _ = ... for intentional ignores
    exclude-functions:
      - (io.Closer).Close
      - (net/http.ResponseWriter).Write
      - os.Setenv
      - os.Unsetenv
      - os.RemoveAll
      - (*github.com/go-rod/rod.Page).Close
      - (*github.com/go-rod/rod.HijackRouter).Stop

  govet:
    enable-all: true
    disable:
      - fieldalignment  # Too noisy
      - shadow          # Too noisy for err variable shadowing

  gofmt:
    simplify: true

  goimports:
    local-prefixes: github.com/Rorqualx/flaresolverr-go

  gosec:
    excludes:
      - G104  # Audit errors not checked - we use errcheck
      - G108  # Profiling endpoint - intentionally enabled for debugging
      - G115  # Integer overflow - safe in our controlled context
      - G302  # Directory permissions - need 0700 for directories
      - G304  # File path from variable - needed for config
      - G404  # Weak random - math/rand is fine for humanize package (mouse/scroll simulation)

  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
    disabled-checks:
      - hugeParam         # Sometimes needed for clarity
      - rangeValCopy      # Sometimes intentional
      - octalLiteral      # 0755 style is still readable
      - httpNoBody        # nil is acceptable for empty body
      - paramTypeCombine  # Explicit params are more readable
      - emptyStringTest   # len(s) == 0 is acceptable

  revive:
    rules:
      - name: blank-imports
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: superfluous-else
      - name: unreachable-code
      - name: redefines-builtin-id

  stylecheck:
    checks:
      - all
      - -ST1000  # Package comments - not required
      - -ST1003  # Underscores in names - we follow Go convention

  misspell:
    locale: US

  prealloc:
    simple: true
    range-loops: true
    for-loops: false  # Can be noisy

  nolintlint:
    require-explanation: true
    require-specific: true

issues:
  exclude-dirs:
    - vendor
    - third_party
  max-issues-per-linter: 50
  max-same-issues: 10

  exclude-rules:
    # Allow long lines in tests
    - path: _test\.go
      linters:
        - lll
        - funlen

    # Allow unchecked errors in tests (cleanup, setup)
    - path: _test\.go
      linters:
        - errcheck

    # Allow unused parameters in test handlers (required by http.HandlerFunc)
    - path: _test\.go
      linters:
        - revive
      text: "unused-parameter"

    # Allow dot imports in tests for testify
    - path: _test\.go
      linters:
        - revive
      text: "dot-imports"

    # Allow empty blocks with explanatory comments
    - linters:
        - revive
      text: "empty-block"

    # Allow intentional type name stuttering for clarity (e.g., solver.SolverConfig)
    - linters:
        - revive
      text: "stutters"

    # Allow unused parameters in interface implementations
    - linters:
        - unparam
      text: "always receives"

    # Allow magic numbers in tests
    - path: _test\.go
      linters:
        - gomnd

  exclude-use-default: false
  exclude:
    # Allow fmt.Errorf without %w when not wrapping
    - "fmt.Errorf can be replaced with errors.New"
